# Example configuration for Azure OpenAI
llm:
  provider: azure_openai
  models:
    azure_openai:
      name: gpt-4o  # Model name in Azure (not deployment name)
      temperature: 0.05
      # Azure-specific settings
      azure_endpoint: https://your-resource.openai.azure.com/
      deployment_name: gpt-4o-deployment  # Your Azure deployment name
      api_version: 2024-05-01-preview  # Azure API version
      timeout: 60  # Request timeout in seconds
      max_retries: 2  # Maximum number of retries

# Graph configuration
graph:
  recursion_limit: 50

# Tools configuration - same as in main config
tools:
  - name: DuckDuckGo
    enabled: true
    type: duckduckgo
    description: Search the internet for current information
    parameters:
      query:
        description: Search query

  - name: Wikipedia
    enabled: true
    type: wikipedia
    description: Search Wikipedia for information
    parameters:
      query:
        description: Search query

  - name: Math
    enabled: true
    type: math
    description: Solve mathematical problems
    parameters:
      expression:
        description: Mathematical expression to evaluate

  - name: Python
    enabled: false
    type: python
    description: Execute Python code for calculations and data processing
    parameters:
      code:
        description: Python code to execute

  - name: DateTime
    enabled: true
    type: datetime
    description: Get current date and time 