# Example configuration for custom OpenAI endpoint (e.g., proxy)
llm:
  provider: openai
  models:
    openai:
      name: gpt-4o
      temperature: 0.05
      # Custom endpoint settings
      base_url: https://your-proxy.example.com/v1  # Custom endpoint URL
      timeout: 90  # Increased timeout for proxy
      max_retries: 3  # More retries for potentially unstable proxy
      # api_version: 2024-05-01-preview  # Uncomment if proxy requires specific API version

# Graph configuration
graph:
  recursion_limit: 50

# Tools configuration - same as in main config
tools:
  - name: DuckDuckGo
    enabled: true
    type: duckduckgo
    description: Search the internet for current information
    parameters:
      query:
        description: Search query

  - name: Wikipedia
    enabled: true
    type: wikipedia
    description: Search Wikipedia for information
    parameters:
      query:
        description: Search query

  - name: Math
    enabled: true
    type: math
    description: Solve mathematical problems
    parameters:
      expression:
        description: Mathematical expression to evaluate

  - name: Python
    enabled: false
    type: python
    description: Execute Python code for calculations and data processing
    parameters:
      code:
        description: Python code to execute

  - name: DateTime
    enabled: true
    type: datetime
    description: Get current date and time 